env: "local"
storage_path: "./storage.db"
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 30s
  user: "Shabby8574"
  password: "user"
db_connection:
  host: "localhost"
  port: "5432"
  db_user: "postgres"
  db_password: "postgres"
  db_name: "postgres"
  ssl_mode: "disable"